// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace oopkr.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230503175200_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Models.Boller", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Plantid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("consumptionPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("currentPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("generatePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Plantid");

                    b.ToTable("Boller");
                });

            modelBuilder.Entity("Models.Plant", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("boillersCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxConsumptionPower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("maxGeneratePower")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("surname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Models.Boller", b =>
                {
                    b.HasOne("Models.Plant", null)
                        .WithMany("bollers")
                        .HasForeignKey("Plantid");
                });

            modelBuilder.Entity("Models.Plant", b =>
                {
                    b.Navigation("bollers");
                });
#pragma warning restore 612, 618
        }
    }
}
